# SPDX-License-Identifier: MIT
---
hyprland_palette:
  name: "Nord"
  cursor_theme: "Nordzy-catppuccin-frappe-blue"
  bg_darkest: "2e3440"
  bg_dark: "3b4252"
  bg_medium: "434c5e"
  bg_light: "4c566a"
  fg_dim: "d8dee9"
  fg_normal: "e5e9f0"
  fg_bright: "eceff4"
  accent_primary: "88c0d0"
  accent_secondary: "81a1c1"
  accent_tertiary: "5e81ac"
  accent_alt: "8fbcbb"
  red: "bf616a"
  orange: "d08770"
  yellow: "ebcb8b"
  green: "a3be8c"
  magenta: "b48ead"
  cal_months: "ffead3"
  cal_days: "ecc6d9"
  cal_weeks: "99ffdd"
  cal_weekdays: "ffcc66"
  cal_today: "ff6699"
