---
galaxy_info:
  role_name: dotfiles
  author: Lucas
  description: Restore portable user dotfiles and desktop configuration.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Fedora
      versions:
        - all
dependencies: []
