version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db_fedora
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: lucas
      POSTGRES_DB: resource
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:

