---
- name: Create molecule instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Start hyprland-instance container
      containers.podman.podman_container:
        name: hyprland-instance
        image: registry.fedoraproject.org/fedora:42
        state: started
        command: /sbin/init
        privileged: true
        systemd: always
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw
        cgroupns: host
