---
- name: Destroy molecule instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Stop and remove hyprland-instance container
      containers.podman.podman_container:
        name: hyprland-instance
        state: absent
