version: '3.8'
services:
  db:
    image: postgres:18
    container_name: postgres_db_fedora
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: lucas
      POSTGRES_DB: resource
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  databasus:
    container_name: databasus
    image: databasus/databasus:latest
    ports:
      - "4005:4005"
    volumes:
      - ./databasus-data:/databasus-data
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:sts
    container_name: portainer
    restart: always

    ports:
      - "9443:9443"
      - "8000:8000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      SEMAPHORE_DB_DIALECT: sqlite
      SEMAPHORE_DB: /etc/semaphore/semaphore.sqlite

      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/

      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin

      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
      TZ: America/Chicago

    volumes:
      - semaphore_data:/etc/semaphore
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      # This line makes Actual available at port 5006 of the device you run the server on,
      # i.e. http://localhost:5006. You can change the first number to change the port, if you want.
      - '5006:5006'
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - ./actual-data:/data
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node scripts/health-check.js']
      # health check using self signed certs
      # test: ['CMD-SHELL', 'NODE_EXTRA_CA_CERTS=/data/selfhost.crt node scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
  myapp:
    image: duplicati/duplicati:latest
    ports:
      - "8200:8200"
    volumes:
      - ./data:/data
    environment:
      # SETTINGS_ENCRYPTION_KEY: "<real encryption key>"
      DUPLICATI__WEBSERVICE_PASSWORD: "JsRules44"
volumes:
  pgdata:
  portainer_data:
  semaphore_data:

