version: '3.8'
services:
  db:
    image: postgres:18
    container_name: postgres_db_fedora
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: lucas
      POSTGRES_DB: resource
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  databasus:
    container_name: databasus
    image: databasus/databasus:latest
    network_mode: host
    ports:
      - "4005:4005"
    volumes:
      - ./databasus-data:/databasus-data
    restart: unless-stopped

volumes:
  pgdata:

