- name: Configure raspberry pi
  hosts: raspberrypi
  become: true
  tasks:
    - name: Get info on docker host and verbose list images
      community.docker.docker_host_info:
        images: true
        verbose_output: true
        disk_usage: true
      register: result

    - name: Ensure minio is installed
      community.docker.docker_container:
        name: minio
        image: quay.io/minio/minio
        state: started
        published_ports:
          - 9000:9000
          - 9001:9001
        mounts:
          - type: bind
            source: /srv/ssd/minio-data
            target: /data
          - type: bind
            source: /srv/ssd/minio.license
            target: /minio.license

    - name: Make sure cockpit is running
      ansible.builtin.systemd_service:
        state: started
        name: cockpit

    - name: check to see what is running on port 53
      ansible.builtin.script: /home/DEV/homelab-dashboard/service-on-port  53
