- name: Configure raspberry pi
  hosts: raspberrypi
  become: true
  vars_files:
    - vault.yml

  vars:
      rclone_version: 1.74.3
      rclone_configs:
        - name: google-drive
          properties:
            type: drive
            client_id: "{{ vault_google_client_id }}"
            client_secret: "{{ vault_google_client_secret }}"
            token: ' {{ vault_google_drive_token }}'

        - name: minio
          properties:
            type: s3
            provider: Minio
            access_key_id: "{{ vault_minio_access_key }}"
            secret_access_key: "{{ vault_minio_secret_key }}"
            endpoint: http://localhost:9000
  roles:
    - stefangweichinger.ansible_rclone

  tasks:
    - name: Get info on docker host and verbose list images
      community.docker.docker_host_info:
        images: true
        verbose_output: true
        disk_usage: true
      register: result
    - name: Ensure MinIO data directory exists
      ansible.builtin.file:
        path: /srv/ssd/minio-data
        state: directory
        owner: lucas
        group: lucas
        mode: "0750"
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: minio.license
        dest: /srv/ssd/minio.license
        owner: lucas
        group: lucas
        mode: '0644'
    - name: Ensure minio is installed
      community.docker.docker_container:
        name: minio
        image: quay.io/minio/aistor/minio:latest
        state: started
        restart_policy: unless-stopped

        pull: always
        published_ports:
          - 9000:9000
          - 9001:9001
        mounts:
          - type: bind
            source: /srv/ssd/minio-data
            target: /data
          - type: bind
            source: /srv/ssd/minio.license
            target: /minio.license
        command:
          - minio
          - server
          - /data
          - --license
          - /minio.license

    - name: Make sure cockpit is running
      ansible.builtin.systemd_service:
        state: started
        name: cockpit
    - name: Ensure Duplicati is enabled and running
      ansible.builtin.systemd_service:
          name: duplicati
          state: started
          enabled: true
    - name: Verify port 53 is open
      ansible.builtin.wait_for:
        port: 53          # Port to check
        state: started  # Ensure the port is actively listening
        timeout: 10       # Fail if not listening within 10 seconds
        host: "0.0.0.0"   # Check all network interfaces (default: 127.0.0.1)
    - name: Verify Pi-hole is running
      ansible.builtin.command: pihole status
      changed_when: false
    - name: Copy backup script
      ansible.builtin.copy:
        src: install-mc.sh
        dest: /usr/local/bin/install-mc.sh
        owner: root
        group: root
        mode: '0755'

    - name: Ensure that mc is installed
      ansible.builtin.command: /usr/local/bin/install-mc.sh
    - name: setup cron script for rclone 
      ansible.builtin.cron:
        name: backup to google drive from minio
        minute: "0"
        hour: "5,2"
        job: >-
          /usr/local/bin/rclone copy
          minio:databasus-backups
          google-drive:minio-backups/postgres-backups
          --config /root/.config/rclone/rclone.conf
          >> /var/log/rclone-minio-backup.log 2>&1

