#SPDX-License-Identifier: MIT-0
---
# tasks file for base
- name: Install base packages
  ansible.builtin.package:
    name:
      - git
      - curl
      - nvim
      - tailscale
      - fd 
      - gh
      - npm
    state: present

- name: configure user.email
  community.general.git_config:
     name: user.email
     scope: global
     value: "lucas.simpson0213@gmail.com"
- name:  configure user.name 
  community.general.git_config: 
    name: user.name 
    scope: global
    value: "Lucas Simpson"
- name: Create ssh key directory
  ansible.builtin.file:
    path: {{github_ssh_dir}}
    state: directory 
    mode: '0700'

- name: Install GitHub private key
  ansible.builtin.copy:
    content: "{{ github_ssh_private_key }}"
    dest: "{{ github_ssh_dir }}/id_ed25519"
    mode: "0600"
  no_log: true


- name: Install ansible language server
  community.general.npm: 
    name: @ansible/ansible-language-server
    global: true
    



