#SPDX-License-Identifier: MIT-0
---
# tasks file for base
- name: Install base packages
  ansible.builtin.dnf:
    name:
      - git
      - curl
      - neovim
      - tailscale
      - fd-find
      - gh
      - npm
      - kitty
      - fish
    state: present



- name: configure user.email
  community.general.git_config:
     name: user.email
     scope: global
     value: "lucas.simpson0213@gmail.com"
- name:  configure user.name 
  community.general.git_config: 
    name: user.name 
    scope: global
    value: "Lucas Simpson"
- name: Create ssh key directory
  ansible.builtin.file:
    path: "/home/lucassimpson/.ssh"
    state: directory 
    mode: '0700'
  become: false

- name: Install GitHub private key
  ansible.builtin.copy:
    content: "{{ private_key_github }}"
    dest: "/home/lucassimpson/.ssh/id_ed25519"
    mode: "0600"
  no_log: true
  become: false


    



