#SPDX-License-Identifier: MIT-0
---
# tasks file for backups
# https://github.com/bcbrookman/ansible-role-duplicati/blob/main/README.md
# copy this role into here
- name: Run duplicati
      docker_container:
        name: backup-container
        image: duplicati/duplicati:2.4.0.0
        state: started
        ports:
          - "8200:8200"
        
          
  
