# SPDX-License-Identifier: MIT
---
# tasks file for hyprland
- name: Enable Hyprland COPR
  community.general.copr:
    name: lionheartp/Hyprland
    state: enabled
  become: true

- name: Install Hyprland environment
  ansible.builtin.dnf:
    name:
      - hyprland
      - hyprpaper
      - hypridle
      - hyprlock
      - hyprpolkitagent
      - sddm
      - mako 
      - waybar
      - foot
      - wl-clipboard
      - grim
      - slurp
      - wofi
      - pamixer
      - pavucontrol
      - waypaper
      - noctalia
      - kde-connect
      - qcalculate
    state: present
  become: true

- name: clone hyprland files into config
  ansible.builtin.git:
    repo: git@github.com:lucassimpson0213/hyprland.git
    dest: /home/lucassimpson/.config/hypr/
    single_branch: yes
    version: intelmac
    accept_newhostkey: true
  become: false

- name: Enable google chromes rpm repo
  ansible.builtin.dnf: 
    name: fedora-workstation-repositories 
  become: true

- name: Ensure the google chrome repository is enabled
  community.general.dnf_config_manager:
    name: google-chrome
    state: enabled
  become: true

- name: install google chrome stable
  ansible.builtin.dnf: 
    name: google-chrome-stable
    state: present

